{
 "title": "Spotify Play History",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "timeGrouping",
    "label": "Time Grouping",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Amount Listened to",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "play",
     "select": [
      [
       { "params": [ "songLength" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Music Listened to Per Hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$timeGrouping" ], "type": "time" }
     ],
     "measurement": "play",
     "select": [
      [
       { "params": [ "songLength" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Snow Patrol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "play",
     "query": "SELECT sum(\"songLength\") FROM \"play\" WHERE (\"artistId\" = '3rIZMv9rysU7JkLzEaC5Jp') AND $timeFilter",
     "select": [
      [
       { "params": [ "songLength" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "artistId", "operator": "=", "value": "3rIZMv9rysU7JkLzEaC5Jp" }
     ]
    }
   ]
  },
  {
   "title": "Take That",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "play",
     "select": [
      [
       { "params": [ "songLength" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "artistName", "operator": "=", "value": "Take That" }
     ]
    }
   ]
  },
  {
   "title": "Song Counter Thing",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT artist_name as \"Artist Name\", track_name as \"Track Name\", COUNT(track_name), SUM(song_length) as \"Total\"\nFROM artist INNER JOIN play_artist pa on artist.artist_id = pa.artist_id INNER JOIN play p on pa.play_id = p.id WHERE id > ${__from}\nGROUP BY track_name, song_length, artist_name"
    }
   ]
  },
  {
   "title": "Artist Counter",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT artist_name as \"Artist Name\", COUNT(artist_id) as \"Count\", SUM(song_length) as \"Total\" FROM\n(SELECT id, song_length, pa.artist_id, artist_name FROM play\n    INNER JOIN play_artist pa on play.id = pa.play_id\n    INNER JOIN artist a on pa.artist_id = a.artist_id\n    WHERE id > ${__from}\n    GROUP BY id, pa.artist_id, artist_name) as all_data GROUP BY all_data.artist_name"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total Distinct Songs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT (case when id > ${__from} then track_id end)) FROM play "
    }
   ]
  },
  {
   "title": "Artists",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM\n(SELECT artist_id FROM\n    (SELECT id, song_length, pa.artist_id, artist_name FROM play\n     INNER JOIN play_artist pa on play.id = pa.play_id\n     INNER JOIN artist a on pa.artist_id = a.artist_id\n     WHERE id > ${__from}\n     GROUP BY id, pa.artist_id, artist_name) as foo GROUP BY foo.artist_id) as faa"
    }
   ]
  },
  {
   "title": "Total Plays",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as \"Total\" FROM play WHERE id > ${__from}"
    }
   ]
  }
 ]
}