version: '2'
services:
  pg-spotify:
    container_name: pg-spotify
    hostname: pg-spotify
    image: postgres:9.6-alpine
    networks:
      - spotify
    ports:
      - "60104:5432"
    environment:
      POSTGRES_USER: spotify
      POSTGRES_PASSWORD: spotify
      POSTGRES_DB: spotify
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /opt/play-history/pg:/var/lib/postgresql/data
    restart: always

  server:
    container_name: spotify-history
    hostname: spotify-history
    image: charlie67/spotify-history:1.1.0
    networks:
      - spotify
    ports:
      - "60102:80"
    environment:
      - SPOTIFY_CLIENT_ID=***
      - SPOTIFY_CLIENT_SECRET=****
      - SPOTIFY_REDIRECT_URI=***
      - POSTGRES_LOCATION=jdbc:postgresql://pg-spotify:5432/spotify
    restart: always
 
networks:
  spotify:
    driver: bridge
