name: Build

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven
    - name: Grant execute permission for mvnw
      run: chmod +x mvnw
    - name: Build
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        TAG_NAME: ${{ github.event.number }}
      run: ./build.sh $DOCKER_USERNAME $DOCKER_PASSWORD $TAG_NAME
